spasiboTelecom/urls.py
from django.contrib import admin
from django.urls import path

from spasiboTelecom import views
from spasiboTelecom.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', contact, name='mainPage'),
    path('success_view', success_view, name='success')
]

spasiboTelecom/forms.py
from django import forms


class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=30, min_length=2, required=True)
    second_name = forms.CharField(max_length=30, min_length=2, required=True)
    last_name = forms.CharField(max_length=50, min_length=2, required=True)
    email_address = forms.EmailField(max_length=50,min_length=5, help_text='Укажите действующий Email', required=True)
    telephone = forms.CharField(max_length=16, min_length=5, help_text='Укажите номер в формате: +7 000 000-00-00', required=True)

spasiboTelecom/views.py
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render
from django.shortcuts import render

from django.shortcuts import render, redirect
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse

# Create your views here.
from .settings import DEFAULT_FROM_EMAIL


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "Соискатель"
            body = {
                'Фамилия': form.cleaned_data['first_name'],
                'Имя': form.cleaned_data['second_name'],
                'Отчество': form.cleaned_data['last_name'],
                'Почта': form.cleaned_data['email_address'],
                'Телефон': form.cleaned_data['telephone'],
            }
            message = str(body)
            message = message.replace("'", "").replace('{', '').replace('}', '').replace(', ', '\n')
            try:
                send_mail(subject, message, None, ['spasibo.telekom@mail.ru'])
            except BadHeaderError:
                return HttpResponse('Найден некорректный заголовок')
            return redirect('success')
    form = ContactForm()
    return render(request, "home.html", {'form': form})


def success_view(request):
    return render(request, 'success_view.html')

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Спасибо-Телеком</title>
    <link rel="icon" href="{% static '/images/favicon.png' %}" type="image/png">
    <link href="{% static '/css/stilesheet.css'%}" rel="stylesheet" type="text/css">
    <script src="{% static 'js/script.js' %}"></script>
</head>
<body>
<div class="gigadiv">
<div class="main">
    <div>
        <img src="{% static '/images/logo.png' %}" style="margin-left: 3%; height: 75px; width: auto; padding: 20px" alt="">
    </div>
    <div>
        <p class="texttop">Спасибо-Телеком приглашает в дружную команду </br> активных и коммуникабельных сотрудников</p>
    </div>
    <div>
        <button class="btn"><a href="#part1" style="text-decoration: none; color: white">Заполнить анкету</a> </button>
    </div>
</div>

<div class="dsm1">
    <p class="headtext">Мы готовы рассмотреть вашу кандидатуру на вакансию:</p>
    <ul>
        <li class="ll1">Специалист по обработке заявок</li>
        <li class="ll1">Офис-менеджер</li>
        <li class="ll1">Оператор колл-центра</li>
    </ul>
</div>

<div class="dsm2">
    <p class="headtext">Вы получите:</p>
    <ul>
        <li class="ll1">Возможность высокого уровня дохода</li>
        <li class="ll1">Работа в комфортных условиях</li>
        <li class="ll1">Доброжелательный коллектив</li>
        <li class="ll1">Бесплатный кофе и чай</li>
        <li class="ll1">Возможность профессионального и карьерного роста</li>
    </ul>
</div>

<div class="dsm3">
    <p class="headtext">Карьерный рост:</p>
     <ul>
        <li class="ll1">Контролер-качества</li>
        <li class="ll1">Супервайзер</li>
        <li class="ll1">Коуч</li>
        <li class="ll1">Руководитель</li>
        <li class="ll1">Иные должности в структуре компании</li>
    </ul>
</div>

<div class="dsm4">
    <p class="headtext">Личностный рост:</p>
    <ul>
        <li class="ll1">Прокачаете навыки ведения переговоров и отработки возражений</li>
        <li class="ll1">Научитесь закрывать сделки</li>
        <li class="ll1">Приобретете уверенность в себе</li>
    </ul>
</div>


<div class="dsm5">
    <p class="headtext">Мы предоставляем следующие гарантии:</p>
    <ul>
        <li class="ll1">Официальное трудоустройство</li>
        <li class="ll1">Своевременная выплата заработной платы</li>
        <li class="ll1">Оснащенное рабочее место</li>
        <li class="ll1">Финансовая мотивация и обучение</li>
        <li class="ll1">Поддержка в период адаптации и во время работы</li>
    </ul>
</div>
<div class="dsm6">
    <p class="headtext">График работы:</p>
    <ul>
        <li class="ll1">Возможность выбрать самостоятельно 2/2 или 5/2</li>
        <li class="ll1">Различные смены: с 08:00 до 14:00 или с 14:00 до 20:00 (допускается индивидуальный график или совмещение)</li>
    </ul>
    <p class="headtext">Достойная оплата труда:</p>
    <ul>
        <li class="ll1">Фиксированная зарплата плюс процент за результат и премия за качество работы</li>
    </ul>
</div>

<div class="dsm" id="part1">
   <div class="divform">
       <form method="post">
           {% csrf_token %}
            <p class="headtext">Расскажите немного о себе, и мы обязательно с вами свяжемся (все поля обязательны для заполнения):</p>
            <p><input type="text" pattern="[^A-Za-z0-9]+$" title="Только русские буквы" minlength="2" maxlength="20" placeholder="Фамилия" name="first_name" id="id_first_name" required> <input type="text" pattern="[^A-Za-z0-9]+$" title="Только русские буквы" minlength="2" maxlength="20" placeholder="Имя" id="id_second_name" name="second_name" required></p>
            <p><input type="text" pattern="[^A-Za-z0-9]+$" title="Только русские буквы" minlength="2" maxlength="20" placeholder="Отчество" name="last_name" id="id_last_name" required> <input type="tel" pattern="[^A-Za-zА-Яа-я]+$" title="Только цифры" minlength="11" maxlength="16" placeholder="Телефон" id="id_telephone" name="telephone" required></p>
            <input type="email" minlength="7" maxlength="40" placeholder="Электронная почта" name="email_address" id="id_email_address" required>
            <p><label for="politics"></label><input type="checkbox" id="politics" onclick="check();" value="" autocomplete="off"/>
            <a class="headtext1">Даю согласие на обработку персональных данных.</a></p>
            <input type="submit" name="submit" class="submit" disabled="" value="Отправить"/>
            <script>
                function check() {
                var submit = document.getElementsByName('submit')[0];
                    if (document.getElementById('politics').checked)
                        submit.disabled = '';
                    else
                        submit.disabled = 'disabled';
                    }
            </script>
        </form>
   </div>


</body>
</html>

templates/success_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Спасибо-Телеком</title>
    <link rel="icon" href="{% static '/images/favicon.png' %}" type="image/png">
    <link href="{% static '/css/stilesheet.css'%}" rel="stylesheet" type="text/css">
    <script src="{% static 'js/script.js' %}"></script>
</head>
<body>
<div class="gigadiv1">
    <div class="dsm">
        <p class="headtext">Ваша заявка зарегистрирована!</p>
        <button class="btn1" onclick="document.location='/'">Вернуться</button>
    </div>
</div>
</body>
</html>